name: Update README with Popular Repos

on:
  schedule:
    - cron: '15 */6 * * *'
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Update README with popular repositories
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://api.github.com/users/Kyugito666/repos?sort=stars&direction=desc"
          max_post_count: 5
          readme_path: 'README.md'
          comment_tag_name: "POPULAR_REPOS"
          template: "- **[$title]($url)**: $description ⭐ $stars"

      - name: Commit and push if changed
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "docs(readme): update popular repos"
          file_pattern: README.md
